# Generated by Django 2.2.6 on 2019-11-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_no', models.IntegerField()),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('cardNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('validity', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('blood_grp', models.CharField(max_length=2)),
            ],
        ),
    ]
