# Generated by Django 2.2.6 on 2019-11-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('dr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='emp_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='healthcenter.Employee'),
        ),
    ]
