# Generated by Django 2.2.6 on 2019-11-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0002_auto_20191105_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_grp',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='OPDRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint_date', models.DateField()),
                ('checked', models.BooleanField(default=False)),
                ('checkup_time', models.TimeField()),
                ('cardNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.Patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.Doctor')),
            ],
        ),
    ]
