# Generated by Django 2.2.6 on 2019-11-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0003_auto_20191105_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='emp_id',
            new_name='emp',
        ),
        migrations.RenameField(
            model_name='opdregistration',
            old_name='cardNo',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='timing',
            old_name='dr_id',
            new_name='dr',
        ),
    ]
