# Generated by Django 2.2.6 on 2019-11-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0004_auto_20191106_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdregistration',
            name='checkup_time',
            field=models.TimeField(default=None),
        ),
    ]
