# Generated by Django 2.2.6 on 2019-11-06 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0006_auto_20191106_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdregistration',
            name='checkup_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
