# Generated by Django 2.2.6 on 2019-11-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0007_auto_20191106_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='dr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.Doctor'),
        ),
        migrations.CreateModel(
            name='MedicalDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField()),
                ('bp', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('temp', models.FloatField()),
                ('diagnosis', models.CharField(max_length=1000)),
                ('pres_given', models.CharField(max_length=1000)),
                ('pathology', models.CharField(max_length=1000)),
                ('opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.OPDRegistration')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.Patient')),
            ],
        ),
    ]
