# Generated by Django 2.2.6 on 2019-11-07 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0008_auto_20191107_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldiagnosis',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
