# Generated by Django 2.2.6 on 2019-11-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Pharmacist', 'Pharmacist'), ('Receptionist', 'Receptionist')], default='Doctor', max_length=100),
        ),
    ]
