# Generated by Django 2.2.6 on 2019-11-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0011_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldiagnosis',
            name='med_given',
            field=models.BooleanField(default=False),
        ),
    ]
