# Generated by Django 2.2.6 on 2019-11-11 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0012_medicaldiagnosis_med_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.MedicalDiagnosis')),
            ],
        ),
    ]
