# Generated by Django 2.2.6 on 2019-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0013_medicinedistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='otp',
            field=models.IntegerField(default=123456),
        ),
        migrations.AddField(
            model_name='feedback',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
