# Generated by Django 2.2.6 on 2020-03-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0014_auto_20191117_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=100)),
                ('cur_stock', models.IntegerField()),
            ],
        ),
    ]
