# Generated by Django 2.2.6 on 2020-03-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0015_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='med_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='cur_stock',
            new_name='shortage_quantity',
        ),
        migrations.RemoveField(
            model_name='medicinedistribution',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='medicine',
            name='authorized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicinedistribution',
            name='medicine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='healthcenter.Medicine'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_from', models.CharField(max_length=1000)),
                ('purchase_order_no', models.IntegerField()),
                ('purchase_order_date', models.DateField()),
                ('bill_no', models.IntegerField()),
                ('billing_date', models.DateField()),
                ('medicine_quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('mf_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('timestamp', models.DateTimeField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.Medicine')),
            ],
        ),
    ]
