# Generated by Django 2.2.6 on 2020-03-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0016_auto_20200312_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_no',
            field=models.CharField(max_length=200),
        ),
    ]
