# Generated by Django 2.2.6 on 2020-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0017_auto_20200313_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
