# Generated by Django 2.2.10 on 2020-03-14 06:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0018_auto_20200313_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologyTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='medicinepurchase',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PathologyTestReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(max_length=1000)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.MedicalDiagnosis')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.PathologyTest')),
            ],
        ),
    ]
