# Generated by Django 2.2.10 on 2020-05-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0019_auto_20200314_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emailid',
            field=models.EmailField(default='amulya.mnnit@gmail.com', max_length=254),
        ),
    ]
