# Generated by Django 2.2.10 on 2020-05-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0022_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emailid',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
