# Generated by Django 2.2.10 on 2020-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0023_auto_20200505_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldiagnosis',
            name='bp',
            field=models.CharField(max_length=1000),
        ),
    ]
