# Generated by Django 2.2.10 on 2020-05-30 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0026_feedback_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdregistration',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
