# Generated by Django 2.2.10 on 2020-05-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0027_opdregistration_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdregistration',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
